drop table if exists dl_cpc.ocpc_industry_aa_report_daily;
create table if not exists dl_cpc.ocpc_industry_aa_report_daily(
    industry                    string,
    all_user_num                int,
    all_unit_num                int,
    ocpc_user_num               int,
    ocpc_unit_num               int,
    cv                          int,
    click                       int,
    show                        int,
    post_cvr                    double,
    cost                        double,
    cpm                         double,
    ocpc_cost                   double,
    ocpc_cost_ratio             double,
    kt_ocpc_cost                double,
    ocpc_in_kt_ratio            double,
    cpa_control_num             int,
    cpa_control_ratio           double,
    ocpc_hidden_num             int,
    ocpc_hidden_cost            double,
    ocpc_hidden_cost_ratio      double,
    hidden_control_num          int,
    hidden_control_ratio        double,
    hit_line_num                int,
    hidden_hit_line_ratio       double,
    avg_hidden_cost             double,
    avg_hidden_budget           double,
    hidden_budget_cost_ratio    double,
    pre_cv                      int,
    cv_ring_ratio               double,
    pre_cost                    double,
    cost_ring_ratio             double,
    pre_post_cvr                double,
    post_cvr_ring_ratio         double,
    pre_cpm                     double,
    cpm_ring_ratio              double
)
partitioned by(`date` string, version string)
stored as parquet;