package com.cpc.spark.ml.recall.featureSystems

import java.io.{File, PrintWriter}
import java.text.SimpleDateFormat
import java.util.Calendar

import com.cpc.spark.common.Murmur3Hash
import org.apache.log4j.{Level, Logger}
import org.apache.spark.sql.functions.{array, udf}
import org.apache.spark.sql.SparkSession
import sys.process._
import scala.collection.mutable

object recall_rec_features {
  Logger.getRootLogger.setLevel(Level.WARN)
  private val default_hash = for (i <- 1 to 37) yield Seq((i - 1, 0, Murmur3Hash.stringHash64("m" + i, 0)))
  def main(args: Array[String]): Unit = {
    val spark = SparkSession.builder().appName("recall_rec_features").enableHiveSupport().getOrCreate()
    val curday = args(0)
    val hour = args(1)
    val cal1 = Calendar.getInstance()
    cal1.setTime(new SimpleDateFormat("yyyy-MM-dd H").parse(s"$curday" + s" " + s"$hour"))
    cal1.add(Calendar.HOUR, 1)
    val dayOneHourLater = new SimpleDateFormat("yyyy-MM-dd").format(cal1.getTime)
    val oneHourLater = new SimpleDateFormat("H").format(cal1.getTime)

    import spark.implicits._
    val rawData = spark.sparkContext.textFile(s"hdfs://emr-cluster2ns2/user/rec/$curday/$hour/")
    val expose_file = s"hdfs://emr-cluster/warehouse/algo_qukan.db/user_docid_exposed_byhour/{day=$dayOneHourLater,day=$curday}/{hour=$oneHourLater,hour=$hour}/*"
    val exposed_rdd = spark.sparkContext.textFile(expose_file)
    val read_file = s"hdfs://emr-cluster2/gobblin/source/lechuan/qukan/qukan_log_v4/{$dayOneHourLater,$curday}/{$oneHourLater,$hour}/300/*"
    val read_rdd = spark.read.parquet(read_file).select($"cookie_id", $"field.content_id.string_type".alias("did")).rdd.map{
      r =>
        val uid = r.getAs[String]("cookie_id")
        val did = r.getAs[String]("did")
        (uid + did, 1)
    }
    val exposed_result = exposed_rdd.map {
      row =>
        val uidAndDid = row.split(",", 2)
        (uidAndDid(0) + uidAndDid(1), uidAndDid(0))
    }
    val feature_rdd = rawData.map {
      r =>
        val lineArray = r.split(" ", 5)
        (lineArray(2) + lineArray(3), r)
    }
    val result = exposed_result.leftOuterJoin(read_rdd).join(feature_rdd).map{
      r =>
        val isclick = if(r._2._1._2.isDefined) {1} else 0
        val lineArray = r._2._2.split(" ", 10)
        val uid = lineArray(2)
        val did = lineArray(3)
        var featureMap = mutable.Map[String, mutable.Seq[String]]()
//        featureMap.update("2", mutable.Seq())
//        featureMap.update("3", mutable.Seq())
        if (lineArray.length < 10){
          null
        } else {
          val featuregroups = lineArray(9).split(";")
          if (featuregroups.length != 2){
            null
          } else {
            //Take only primitive features
            for (index <- 0 until featuregroups.length-1){
              val features = featuregroups(index).split(" ")
              features.foreach {
                feature =>
                  val featureInfo = feature.split(":")
                  if(featureInfo.length != 5){
                    null
                  } else {
                    val slotid = featureInfo(0)
                    if(featureMap.contains(slotid)){
                      val updatedValue = featureMap(slotid) ++ Seq(featureInfo(1))
                      featureMap.update(slotid, updatedValue)
                    } else {
                      featureMap.update(slotid, mutable.Seq(featureInfo(1)))
                    }
                  }
              }
            }
            featuresResult(
              uid = uid,
              did = did,
              isclick = isclick,
              slotid1 = if(featureMap.contains("1")){featureMap("1")} else null,
              slotid2 = if(featureMap.contains("2")){featureMap("2")} else null,
              slotid3 =if(featureMap.contains("3")){featureMap("3")} else null,
              slotid4 =if(featureMap.contains("4")){featureMap("4")} else null,
              slotid5 =if(featureMap.contains("5")){featureMap("5")} else null,
              slotid6 =if(featureMap.contains("6")){featureMap("6")} else null,
              slotid7 =if(featureMap.contains("7")){featureMap("7")} else null,
              slotid8 =if(featureMap.contains("8")){featureMap("8")} else null,
              slotid9 =if(featureMap.contains("9")){featureMap("9")} else null,
              slotid10 =if(featureMap.contains("10")){featureMap("10")} else null,
              slotid11 =if(featureMap.contains("11")){featureMap("11")} else null,
              slotid12 =if(featureMap.contains("12")){featureMap("12")} else null,
              slotid13 =if(featureMap.contains("13")){featureMap("13")} else null,
              slotid14 =if(featureMap.contains("14")){featureMap("14")} else null,
              slotid15 =if(featureMap.contains("15")){featureMap("15")} else null,
              slotid16 =if(featureMap.contains("16")){featureMap("16")} else null,
              slotid17 =if(featureMap.contains("17")){featureMap("17")} else null,
              slotid18 =if(featureMap.contains("18")){featureMap("18")} else null,
              slotid19 =if(featureMap.contains("19")){featureMap("19")} else null,
              slotid20 =if(featureMap.contains("20")){featureMap("20")} else null,
              slotid21 =if(featureMap.contains("21")){featureMap("21")} else null,
              slotid22 =if(featureMap.contains("22")){featureMap("22")} else null,
              slotid23 =if(featureMap.contains("23")){featureMap("23")} else null,
              slotid24 =if(featureMap.contains("24")){featureMap("24")} else null,
              slotid25 =if(featureMap.contains("25")){featureMap("25")} else null,
              slotid26 =if(featureMap.contains("26")){featureMap("26")} else null,
              slotid27 =if(featureMap.contains("27")){featureMap("27")} else null,
              slotid28 =if(featureMap.contains("28")){featureMap("28")} else null,
              slotid29 =if(featureMap.contains("29")){featureMap("29")} else null,
              slotid30 =if(featureMap.contains("30")){featureMap("30")} else null,
              slotid31 =if(featureMap.contains("31")){featureMap("31")} else null,
              slotid32 =if(featureMap.contains("32")){featureMap("32")} else null,
              slotid33 =if(featureMap.contains("33")){featureMap("33")} else null,
              slotid34 =if(featureMap.contains("34")){featureMap("34")} else null,
              slotid35 =if(featureMap.contains("35")){featureMap("35")} else null,
              slotid36 =if(featureMap.contains("36")){featureMap("36")} else null,
              slotid37 =if(featureMap.contains("37")){featureMap("37")} else null,
              slotid38 =if(featureMap.contains("38")){featureMap("38")} else null,
              slotid39 =if(featureMap.contains("39")){featureMap("39")} else null,
              slotid40 =if(featureMap.contains("40")){featureMap("40")} else null,
              slotid41 =if(featureMap.contains("41")){featureMap("41")} else null,
              slotid42 =if(featureMap.contains("42")){featureMap("42")} else null,
              slotid43 =if(featureMap.contains("43")){featureMap("43")} else null,
              slotid44 =if(featureMap.contains("44")){featureMap("44")} else null,
              slotid45 =if(featureMap.contains("45")){featureMap("45")} else null,
              slotid46 =if(featureMap.contains("46")){featureMap("46")} else null,
              slotid47 =if(featureMap.contains("47")){featureMap("47")} else null,
              slotid48 =if(featureMap.contains("48")){featureMap("48")} else null,
              slotid49 =if(featureMap.contains("49")){featureMap("49")} else null,
              slotid50 =if(featureMap.contains("50")){featureMap("50")} else null,
              slotid51 =if(featureMap.contains("51")){featureMap("51")} else null,
              slotid52 =if(featureMap.contains("52")){featureMap("52")} else null,
              slotid53 =if(featureMap.contains("53")){featureMap("53")} else null,
              slotid54 =if(featureMap.contains("54")){featureMap("54")} else null,
              slotid55 =if(featureMap.contains("55")){featureMap("55")} else null,
              slotid56 =if(featureMap.contains("56")){featureMap("56")} else null,
              slotid57 =if(featureMap.contains("57")){featureMap("57")} else null,
              slotid58 =if(featureMap.contains("58")){featureMap("58")} else null,
              slotid59 =if(featureMap.contains("59")){featureMap("59")} else null,
              slotid60 =if(featureMap.contains("60")){featureMap("60")} else null,
              slotid61 =if(featureMap.contains("61")){featureMap("61")} else null,
              slotid62 =if(featureMap.contains("62")){featureMap("62")} else null,
              slotid63 =if(featureMap.contains("63")){featureMap("63")} else null,
              slotid64 =if(featureMap.contains("64")){featureMap("64")} else null,
              slotid65 =if(featureMap.contains("65")){featureMap("65")} else null,
              slotid66 =if(featureMap.contains("66")){featureMap("66")} else null,
              slotid67 =if(featureMap.contains("67")){featureMap("67")} else null,
              slotid68 =if(featureMap.contains("68")){featureMap("68")} else null,
              slotid69 =if(featureMap.contains("69")){featureMap("69")} else null,
              slotid70 =if(featureMap.contains("70")){featureMap("70")} else null,
              slotid71 =if(featureMap.contains("71")){featureMap("71")} else null,
              slotid72 =if(featureMap.contains("72")){featureMap("72")} else null,
              slotid73 =if(featureMap.contains("73")){featureMap("73")} else null,
              slotid74 =if(featureMap.contains("74")){featureMap("74")} else null,
              slotid75 =if(featureMap.contains("75")){featureMap("75")} else null,
              slotid76 =if(featureMap.contains("76")){featureMap("76")} else null,
              slotid77 =if(featureMap.contains("77")){featureMap("77")} else null,
              slotid78 =if(featureMap.contains("78")){featureMap("78")} else null,
              slotid79 =if(featureMap.contains("79")){featureMap("79")} else null,
              slotid80 =if(featureMap.contains("80")){featureMap("80")} else null,
              slotid81 =if(featureMap.contains("81")){featureMap("81")} else null,
              slotid82 =if(featureMap.contains("82")){featureMap("82")} else null,
              slotid83 =if(featureMap.contains("83")){featureMap("83")} else null,
              slotid84 =if(featureMap.contains("84")){featureMap("84")} else null,
              slotid85 =if(featureMap.contains("85")){featureMap("85")} else null,
              slotid86 =if(featureMap.contains("86")){featureMap("86")} else null,
              slotid87 =if(featureMap.contains("87")){featureMap("87")} else null,
              slotid88 =if(featureMap.contains("88")){featureMap("88")} else null,
              slotid89 =if(featureMap.contains("89")){featureMap("89")} else null,
              slotid90 =if(featureMap.contains("90")){featureMap("90")} else null,
              slotid91 =if(featureMap.contains("91")){featureMap("91")} else null,
              slotid92 =if(featureMap.contains("92")){featureMap("92")} else null,
              slotid93 =if(featureMap.contains("93")){featureMap("93")} else null,
              slotid94 =if(featureMap.contains("94")){featureMap("94")} else null,
              slotid95 =if(featureMap.contains("95")){featureMap("95")} else null,
              slotid96 =if(featureMap.contains("96")){featureMap("96")} else null,
              slotid97 =if(featureMap.contains("97")){featureMap("97")} else null,
              slotid98 =if(featureMap.contains("98")){featureMap("98")} else null,
              slotid99 =if(featureMap.contains("99")){featureMap("99")} else null,
              slotid100 =if(featureMap.contains("100")){featureMap("100")} else null,
              slotid101 =if(featureMap.contains("101")){featureMap("101")} else null,
              slotid102 =if(featureMap.contains("102")){featureMap("102")} else null,
              slotid103 =if(featureMap.contains("103")){featureMap("103")} else null,
              slotid104 =if(featureMap.contains("104")){featureMap("104")} else null,
              slotid105 =if(featureMap.contains("105")){featureMap("105")} else null,
              slotid106 =if(featureMap.contains("106")){featureMap("106")} else null,
              slotid107 =if(featureMap.contains("107")){featureMap("107")} else null,
              slotid108 =if(featureMap.contains("108")){featureMap("108")} else null,
              slotid109 =if(featureMap.contains("109")){featureMap("109")} else null,
              slotid110 =if(featureMap.contains("110")){featureMap("110")} else null,
              slotid111 =if(featureMap.contains("111")){featureMap("111")} else null,
              slotid112 =if(featureMap.contains("112")){featureMap("112")} else null,
              slotid113 =if(featureMap.contains("113")){featureMap("113")} else null,
              slotid114 =if(featureMap.contains("114")){featureMap("114")} else null,
              slotid115 =if(featureMap.contains("115")){featureMap("115")} else null,
              slotid116 =if(featureMap.contains("116")){featureMap("116")} else null,
              slotid117 =if(featureMap.contains("117")){featureMap("117")} else null,
              slotid118 =if(featureMap.contains("118")){featureMap("118")} else null,
              slotid119 =if(featureMap.contains("119")){featureMap("119")} else null,
              slotid120 =if(featureMap.contains("120")){featureMap("120")} else null,
              slotid121 =if(featureMap.contains("121")){featureMap("121")} else null,
              slotid122 =if(featureMap.contains("122")){featureMap("122")} else null,
              slotid123 =if(featureMap.contains("123")){featureMap("123")} else null,
              slotid124 =if(featureMap.contains("124")){featureMap("124")} else null,
              slotid125 =if(featureMap.contains("125")){featureMap("125")} else null,
              slotid126 =if(featureMap.contains("126")){featureMap("126")} else null,
              slotid127 =if(featureMap.contains("127")){featureMap("127")} else null,
              slotid128 =if(featureMap.contains("128")){featureMap("128")} else null,
              slotid129 =if(featureMap.contains("129")){featureMap("129")} else null,
              slotid130 =if(featureMap.contains("130")){featureMap("130")} else null,
              slotid131 =if(featureMap.contains("131")){featureMap("131")} else null,
              slotid132 =if(featureMap.contains("132")){featureMap("132")} else null,
              slotid133 =if(featureMap.contains("133")){featureMap("133")} else null,
              slotid134 =if(featureMap.contains("134")){featureMap("134")} else null,
              slotid135 =if(featureMap.contains("135")){featureMap("135")} else null,
              slotid136 =if(featureMap.contains("136")){featureMap("136")} else null,
              slotid137 =if(featureMap.contains("137")){featureMap("137")} else null,
              slotid138 =if(featureMap.contains("138")){featureMap("138")} else null,
              slotid139 =if(featureMap.contains("139")){featureMap("139")} else null,
              slotid140 =if(featureMap.contains("140")){featureMap("140")} else null,
              slotid141 =if(featureMap.contains("141")){featureMap("141")} else null,
              slotid142 =if(featureMap.contains("142")){featureMap("142")} else null,
              slotid143 =if(featureMap.contains("143")){featureMap("143")} else null,
              slotid144 =if(featureMap.contains("144")){featureMap("144")} else null,
              slotid145 =if(featureMap.contains("145")){featureMap("145")} else null,
              slotid146 =if(featureMap.contains("146")){featureMap("146")} else null,
              slotid147 =if(featureMap.contains("147")){featureMap("147")} else null,
              slotid148 =if(featureMap.contains("148")){featureMap("148")} else null,
              slotid149 =if(featureMap.contains("149")){featureMap("149")} else null,
              slotid150 =if(featureMap.contains("150")){featureMap("150")} else null,
              slotid151 =if(featureMap.contains("151")){featureMap("151")} else null,
              slotid152 =if(featureMap.contains("152")){featureMap("152")} else null,
              slotid153 =if(featureMap.contains("153")){featureMap("153")} else null,
              slotid154 =if(featureMap.contains("154")){featureMap("154")} else null,
              slotid155 =if(featureMap.contains("155")){featureMap("155")} else null,
              slotid156 =if(featureMap.contains("156")){featureMap("156")} else null,
              slotid157 =if(featureMap.contains("157")){featureMap("157")} else null,
              slotid158 =if(featureMap.contains("158")){featureMap("158")} else null,
              slotid159 =if(featureMap.contains("159")){featureMap("159")} else null,
              slotid160 =if(featureMap.contains("160")){featureMap("160")} else null,
              slotid161 =if(featureMap.contains("161")){featureMap("161")} else null,
              slotid162 =if(featureMap.contains("162")){featureMap("162")} else null,
              slotid163 =if(featureMap.contains("163")){featureMap("163")} else null,
              slotid164 =if(featureMap.contains("164")){featureMap("164")} else null,
              slotid165 =if(featureMap.contains("165")){featureMap("165")} else null,
              slotid166 =if(featureMap.contains("166")){featureMap("166")} else null,
              slotid167 =if(featureMap.contains("167")){featureMap("167")} else null,
              slotid168 =if(featureMap.contains("168")){featureMap("168")} else null,
              slotid169 =if(featureMap.contains("169")){featureMap("169")} else null,
              slotid170 =if(featureMap.contains("170")){featureMap("170")} else null,
              slotid171 =if(featureMap.contains("171")){featureMap("171")} else null,
              slotid172 =if(featureMap.contains("172")){featureMap("172")} else null,
              slotid173 =if(featureMap.contains("173")){featureMap("173")} else null,
              slotid174 =if(featureMap.contains("174")){featureMap("174")} else null,
              slotid175 =if(featureMap.contains("175")){featureMap("175")} else null,
              slotid176 =if(featureMap.contains("176")){featureMap("176")} else null,
              slotid177 =if(featureMap.contains("177")){featureMap("177")} else null,
              slotid178 =if(featureMap.contains("178")){featureMap("178")} else null,
              slotid179 =if(featureMap.contains("179")){featureMap("179")} else null,
              slotid180 =if(featureMap.contains("180")){featureMap("180")} else null,
              slotid181 =if(featureMap.contains("181")){featureMap("181")} else null,
              slotid182 =if(featureMap.contains("182")){featureMap("182")} else null,
              slotid183 =if(featureMap.contains("183")){featureMap("183")} else null,
              slotid184 =if(featureMap.contains("184")){featureMap("184")} else null,
              slotid185 =if(featureMap.contains("185")){featureMap("185")} else null,
              slotid186 =if(featureMap.contains("186")){featureMap("186")} else null,
              slotid187 =if(featureMap.contains("187")){featureMap("187")} else null,
              slotid188 =if(featureMap.contains("188")){featureMap("188")} else null,
              slotid189 =if(featureMap.contains("189")){featureMap("189")} else null,
              slotid190 =if(featureMap.contains("190")){featureMap("190")} else null,
              slotid191 =if(featureMap.contains("191")){featureMap("191")} else null,
              slotid192 =if(featureMap.contains("192")){featureMap("192")} else null,
              slotid193 =if(featureMap.contains("193")){featureMap("193")} else null,
              slotid194 =if(featureMap.contains("194")){featureMap("194")} else null,
              slotid195 =if(featureMap.contains("195")){featureMap("195")} else null,
              slotid196 =if(featureMap.contains("196")){featureMap("196")} else null,
              slotid197 =if(featureMap.contains("197")){featureMap("197")} else null,
              slotid198 =if(featureMap.contains("198")){featureMap("198")} else null,
              slotid199 =if(featureMap.contains("199")){featureMap("199")} else null,
              slotid200 =if(featureMap.contains("200")){featureMap("200")} else null,
              slotid201 =if(featureMap.contains("201")){featureMap("201")} else null,
              slotid202 =if(featureMap.contains("202")){featureMap("202")} else null,
              slotid203 =if(featureMap.contains("203")){featureMap("203")} else null,
              slotid204 =if(featureMap.contains("204")){featureMap("204")} else null,
              slotid205 =if(featureMap.contains("205")){featureMap("205")} else null,
              slotid206 =if(featureMap.contains("206")){featureMap("206")} else null,
              slotid207 =if(featureMap.contains("207")){featureMap("207")} else null,
              slotid208 =if(featureMap.contains("208")){featureMap("208")} else null,
              slotid209 =if(featureMap.contains("209")){featureMap("209")} else null,
              slotid210 =if(featureMap.contains("210")){featureMap("210")} else null,
              slotid211 =if(featureMap.contains("211")){featureMap("211")} else null,
              slotid212 =if(featureMap.contains("212")){featureMap("212")} else null,
              slotid213 =if(featureMap.contains("213")){featureMap("213")} else null,
              slotid214 =if(featureMap.contains("214")){featureMap("214")} else null,
              slotid215 =if(featureMap.contains("215")){featureMap("215")} else null,
              slotid216 =if(featureMap.contains("216")){featureMap("216")} else null,
              slotid217 =if(featureMap.contains("217")){featureMap("217")} else null,
              slotid218 =if(featureMap.contains("218")){featureMap("218")} else null,
              slotid219 =if(featureMap.contains("219")){featureMap("219")} else null,
              slotid220 =if(featureMap.contains("220")){featureMap("220")} else null,
              slotid221 =if(featureMap.contains("221")){featureMap("221")} else null,
              slotid222 =if(featureMap.contains("222")){featureMap("222")} else null,
              slotid223 =if(featureMap.contains("223")){featureMap("223")} else null,
              slotid224 =if(featureMap.contains("224")){featureMap("224")} else null,
              slotid225 =if(featureMap.contains("225")){featureMap("225")} else null,
              slotid226 =if(featureMap.contains("226")){featureMap("226")} else null
            )
          }
        }
    }.filter(_ != null).toDF("uid",
      "did",
      "isclick",
      "slotid1",
      "slotid2",
      "slotid3",
      "slotid4",
      "slotid5",
      "slotid6",
      "slotid7",
      "slotid8",
      "slotid9",
      "slotid10",
      "slotid11",
      "slotid12",
      "slotid13",
      "slotid14",
      "slotid15",
      "slotid16",
      "slotid17",
      "slotid18",
      "slotid19",
      "slotid20",
      "slotid21",
      "slotid22",
      "slotid23",
      "slotid24",
      "slotid25",
      "slotid26",
      "slotid27",
      "slotid28",
      "slotid29",
      "slotid30",
      "slotid31",
      "slotid32",
      "slotid33",
      "slotid34",
      "slotid35",
      "slotid36",
      "slotid37",
      "slotid38",
      "slotid39",
      "slotid40",
      "slotid41",
      "slotid42",
      "slotid43",
      "slotid44",
      "slotid45",
      "slotid46",
      "slotid47",
      "slotid48",
      "slotid49",
      "slotid50",
      "slotid51",
      "slotid52",
      "slotid53",
      "slotid54",
      "slotid55",
      "slotid56",
      "slotid57",
      "slotid58",
      "slotid59",
      "slotid60",
      "slotid61",
      "slotid62",
      "slotid63",
      "slotid64",
      "slotid65",
      "slotid66",
      "slotid67",
      "slotid68",
      "slotid69",
      "slotid70",
      "slotid71",
      "slotid72",
      "slotid73",
      "slotid74",
      "slotid75",
      "slotid76",
      "slotid77",
      "slotid78",
      "slotid79",
      "slotid80",
      "slotid81",
      "slotid82",
      "slotid83",
      "slotid84",
      "slotid85",
      "slotid86",
      "slotid87",
      "slotid88",
      "slotid89",
      "slotid90",
      "slotid91",
      "slotid92",
      "slotid93",
      "slotid94",
      "slotid95",
      "slotid96",
      "slotid97",
      "slotid98",
      "slotid99",
      "slotid100",
      "slotid101",
      "slotid102",
      "slotid103",
      "slotid104",
      "slotid105",
      "slotid106",
      "slotid107",
      "slotid108",
      "slotid109",
      "slotid110",
      "slotid111",
      "slotid112",
      "slotid113",
      "slotid114",
      "slotid115",
      "slotid116",
      "slotid117",
      "slotid118",
      "slotid119",
      "slotid120",
      "slotid121",
      "slotid122",
      "slotid123",
      "slotid124",
      "slotid125",
      "slotid126",
      "slotid127",
      "slotid128",
      "slotid129",
      "slotid130",
      "slotid131",
      "slotid132",
      "slotid133",
      "slotid134",
      "slotid135",
      "slotid136",
      "slotid137",
      "slotid138",
      "slotid139",
      "slotid140",
      "slotid141",
      "slotid142",
      "slotid143",
      "slotid144",
      "slotid145",
      "slotid146",
      "slotid147",
      "slotid148",
      "slotid149",
      "slotid150",
      "slotid151",
      "slotid152",
      "slotid153",
      "slotid154",
      "slotid155",
      "slotid156",
      "slotid157",
      "slotid158",
      "slotid159",
      "slotid160",
      "slotid161",
      "slotid162",
      "slotid163",
      "slotid164",
      "slotid165",
      "slotid166",
      "slotid167",
      "slotid168",
      "slotid169",
      "slotid170",
      "slotid171",
      "slotid172",
      "slotid173",
      "slotid174",
      "slotid175",
      "slotid176",
      "slotid177",
      "slotid178",
      "slotid179",
      "slotid180",
      "slotid181",
      "slotid182",
      "slotid183",
      "slotid184",
      "slotid185",
      "slotid186",
      "slotid187",
      "slotid188",
      "slotid189",
      "slotid190",
      "slotid191",
      "slotid192",
      "slotid193",
      "slotid194",
      "slotid195",
      "slotid196",
      "slotid197",
      "slotid198",
      "slotid199",
      "slotid200",
      "slotid201",
      "slotid202",
      "slotid203",
      "slotid204",
      "slotid205",
      "slotid206",
      "slotid207",
      "slotid208",
      "slotid209",
      "slotid210",
      "slotid211",
      "slotid212",
      "slotid213",
      "slotid214",
      "slotid215",
      "slotid216",
      "slotid217",
      "slotid218",
      "slotid219",
      "slotid220",
      "slotid221",
      "slotid222",
      "slotid223",
      "slotid224",
      "slotid225",
      "slotid226"
    )
//    result.coalesce(100).write.mode(SaveMode.Append).parquet("hdfs://emr-cluster/warehouse/dl_cpc.db/cdl_cpc.recall_rec_feature/%s/%s".format(curday, hour))
//    val sql =
//      """
//        |ALTER TABLE dl_cpc.recall_rec_feature add if not exists PARTITION (day="%s", hour="%s")  LOCATION
//        |       'hdfs://emr-cluster/warehouse/dl_cpc.db/recall_rec_feature/%s/%s'
//                """.stripMargin.format(curday, hour, curday, hour)
//    spark.sql(sql)
    result.repartition(150).createOrReplaceTempView("feature_result")
    spark.sql(
      s"""
         |insert overwrite table dl_cpc.recall_rec_feature partition(day='$curday', hour='$hour')
         |select * from feature_result
       """.stripMargin)

    val sample = spark.sql(
      s"""
         |select if(isclick>0, array(1,0), array(0,1)) as label, * from dl_cpc.recall_rec_feature where day='$curday' and hour='$hour'
       """.stripMargin).select($"uid", $"label", mkSparseFeature_m(array(
      hashSeq("m1", "string")($"slotid1").alias("slotid1"),
      hashSeq("m2", "string")($"slotid2").alias("slotid2"),
      hashSeq("m3", "string")($"slotid3").alias("slotid3"),
      hashSeq("m4", "string")($"slotid4").alias("slotid4"),
      hashSeq("m5", "string")($"slotid5").alias("slotid5"),
      hashSeq("m6", "string")($"slotid6").alias("slotid6"),
      hashSeq("m7", "string")($"slotid7").alias("slotid7"),
      hashSeq("m8", "string")($"slotid8").alias("slotid8"),
      hashSeq("m9", "string")($"slotid9").alias("slotid9"),
      hashSeq("m10", "string")($"slotid10").alias("slotid10"),
      hashSeq("m11", "string")($"slotid11").alias("slotid11"),
      hashSeq("m12", "string")($"slotid12").alias("slotid12"),
      hashSeq("m13", "string")($"slotid13").alias("slotid13"),
      hashSeq("m14", "string")($"slotid14").alias("slotid14"),
      hashSeq("m15", "string")($"slotid15").alias("slotid15"),
      hashSeq("m16", "string")($"slotid16").alias("slotid16"),
      hashSeq("m17", "string")($"slotid17").alias("slotid17"),
      hashSeq("m18", "string")($"slotid18").alias("slotid18"),
      hashSeq("m19", "string")($"slotid19").alias("slotid19"),
      hashSeq("m20", "string")($"slotid20").alias("slotid20"),
      hashSeq("m21", "string")($"slotid21").alias("slotid21"),
      hashSeq("m22", "string")($"slotid22").alias("slotid22"),
      hashSeq("m23", "string")($"slotid23").alias("slotid23"),
      hashSeq("m24", "string")($"slotid24").alias("slotid24"),
      hashSeq("m25", "string")($"slotid25").alias("slotid25"),
      hashSeq("m26", "string")($"slotid26").alias("slotid26"),
      hashSeq("m27", "string")($"slotid27").alias("slotid27"),
      hashSeq("m28", "string")($"slotid28").alias("slotid28"),
      hashSeq("m29", "string")($"slotid29").alias("slotid29"),
      hashSeq("m30", "string")($"slotid30").alias("slotid30"),
      hashSeq("m31", "string")($"slotid31").alias("slotid31"),
      hashSeq("m32", "string")($"slotid32").alias("slotid32"),
      hashSeq("m33", "string")($"slotid33").alias("slotid33"),
      hashSeq("m34", "string")($"slotid34").alias("slotid34"),
      hashSeq("m35", "string")($"slotid35").alias("slotid35"),
      hashSeq("m36", "string")($"slotid36").alias("slotid36"),
      hashSeq("m37", "string")($"slotid37").alias("slotid37"),
      hashSeq("m38", "string")($"slotid38").alias("slotid38"),
      hashSeq("m39", "string")($"slotid39").alias("slotid39"),
      hashSeq("m40", "string")($"slotid40").alias("slotid40"),
      hashSeq("m41", "string")($"slotid41").alias("slotid41"),
      hashSeq("m42", "string")($"slotid42").alias("slotid42"),
      hashSeq("m43", "string")($"slotid43").alias("slotid43"),
      hashSeq("m44", "string")($"slotid44").alias("slotid44"),
      hashSeq("m45", "string")($"slotid45").alias("slotid45"),
      hashSeq("m46", "string")($"slotid46").alias("slotid46"),
      hashSeq("m47", "string")($"slotid47").alias("slotid47"),
      hashSeq("m48", "string")($"slotid48").alias("slotid48"),
      hashSeq("m49", "string")($"slotid49").alias("slotid49"),
      hashSeq("m50", "string")($"slotid50").alias("slotid50"),
      hashSeq("m51", "string")($"slotid51").alias("slotid51"),
      hashSeq("m52", "string")($"slotid52").alias("slotid52"),
      hashSeq("m53", "string")($"slotid53").alias("slotid53"),
      hashSeq("m54", "string")($"slotid54").alias("slotid54"),
      hashSeq("m55", "string")($"slotid55").alias("slotid55"),
      hashSeq("m56", "string")($"slotid56").alias("slotid56"),
      hashSeq("m57", "string")($"slotid57").alias("slotid57"),
      hashSeq("m58", "string")($"slotid58").alias("slotid58"),
      hashSeq("m59", "string")($"slotid59").alias("slotid59"),
      hashSeq("m60", "string")($"slotid60").alias("slotid60"),
      hashSeq("m61", "string")($"slotid61").alias("slotid61"),
      hashSeq("m62", "string")($"slotid62").alias("slotid62"),
      hashSeq("m63", "string")($"slotid63").alias("slotid63"),
      hashSeq("m64", "string")($"slotid64").alias("slotid64"),
      hashSeq("m65", "string")($"slotid65").alias("slotid65"),
      hashSeq("m66", "string")($"slotid66").alias("slotid66"),
      hashSeq("m67", "string")($"slotid67").alias("slotid67"),
      hashSeq("m68", "string")($"slotid68").alias("slotid68"),
      hashSeq("m69", "string")($"slotid69").alias("slotid69"),
      hashSeq("m70", "string")($"slotid70").alias("slotid70"),
      hashSeq("m71", "string")($"slotid71").alias("slotid71"),
      hashSeq("m72", "string")($"slotid72").alias("slotid72"),
      hashSeq("m73", "string")($"slotid73").alias("slotid73"),
      hashSeq("m74", "string")($"slotid74").alias("slotid74"),
      hashSeq("m75", "string")($"slotid75").alias("slotid75"),
      hashSeq("m76", "string")($"slotid76").alias("slotid76"),
      hashSeq("m77", "string")($"slotid77").alias("slotid77"),
      hashSeq("m78", "string")($"slotid78").alias("slotid78"),
      hashSeq("m79", "string")($"slotid79").alias("slotid79"),
      hashSeq("m80", "string")($"slotid80").alias("slotid80"),
      hashSeq("m81", "string")($"slotid81").alias("slotid81"),
      hashSeq("m82", "string")($"slotid82").alias("slotid82"),
      hashSeq("m83", "string")($"slotid83").alias("slotid83"),
      hashSeq("m84", "string")($"slotid84").alias("slotid84"),
      hashSeq("m85", "string")($"slotid85").alias("slotid85"),
      hashSeq("m86", "string")($"slotid86").alias("slotid86"),
      hashSeq("m87", "string")($"slotid87").alias("slotid87"),
      hashSeq("m88", "string")($"slotid88").alias("slotid88"),
      hashSeq("m89", "string")($"slotid89").alias("slotid89"),
      hashSeq("m90", "string")($"slotid90").alias("slotid90"),
      hashSeq("m91", "string")($"slotid91").alias("slotid91"),
      hashSeq("m92", "string")($"slotid92").alias("slotid92"),
      hashSeq("m93", "string")($"slotid93").alias("slotid93"),
      hashSeq("m94", "string")($"slotid94").alias("slotid94"),
      hashSeq("m95", "string")($"slotid95").alias("slotid95"),
      hashSeq("m96", "string")($"slotid96").alias("slotid96"),
      hashSeq("m97", "string")($"slotid97").alias("slotid97"),
      hashSeq("m98", "string")($"slotid98").alias("slotid98"),
      hashSeq("m99", "string")($"slotid99").alias("slotid99"),
      hashSeq("m100", "string")($"slotid100").alias("slotid100"),
      hashSeq("m101", "string")($"slotid101").alias("slotid101"),
      hashSeq("m102", "string")($"slotid102").alias("slotid102"),
      hashSeq("m103", "string")($"slotid103").alias("slotid103"),
      hashSeq("m104", "string")($"slotid104").alias("slotid104"),
      hashSeq("m105", "string")($"slotid105").alias("slotid105"),
      hashSeq("m106", "string")($"slotid106").alias("slotid106"),
      hashSeq("m107", "string")($"slotid107").alias("slotid107"),
      hashSeq("m108", "string")($"slotid108").alias("slotid108"),
      hashSeq("m109", "string")($"slotid109").alias("slotid109"),
      hashSeq("m110", "string")($"slotid110").alias("slotid110"),
      hashSeq("m111", "string")($"slotid111").alias("slotid111"),
      hashSeq("m112", "string")($"slotid112").alias("slotid112"),
      hashSeq("m113", "string")($"slotid113").alias("slotid113"),
      hashSeq("m114", "string")($"slotid114").alias("slotid114"),
      hashSeq("m115", "string")($"slotid115").alias("slotid115"),
      hashSeq("m116", "string")($"slotid116").alias("slotid116"),
      hashSeq("m117", "string")($"slotid117").alias("slotid117"),
      hashSeq("m118", "string")($"slotid118").alias("slotid118"),
      hashSeq("m119", "string")($"slotid119").alias("slotid119"),
      hashSeq("m120", "string")($"slotid120").alias("slotid120"),
      hashSeq("m121", "string")($"slotid121").alias("slotid121"),
      hashSeq("m122", "string")($"slotid122").alias("slotid122"),
      hashSeq("m123", "string")($"slotid123").alias("slotid123"),
      hashSeq("m124", "string")($"slotid124").alias("slotid124"),
      hashSeq("m125", "string")($"slotid125").alias("slotid125"),
      hashSeq("m126", "string")($"slotid126").alias("slotid126"),
      hashSeq("m127", "string")($"slotid127").alias("slotid127"),
      hashSeq("m128", "string")($"slotid128").alias("slotid128"),
      hashSeq("m129", "string")($"slotid129").alias("slotid129"),
      hashSeq("m130", "string")($"slotid130").alias("slotid130"),
      hashSeq("m131", "string")($"slotid131").alias("slotid131"),
      hashSeq("m132", "string")($"slotid132").alias("slotid132"),
      hashSeq("m133", "string")($"slotid133").alias("slotid133"),
      hashSeq("m134", "string")($"slotid134").alias("slotid134"),
      hashSeq("m135", "string")($"slotid135").alias("slotid135"),
      hashSeq("m136", "string")($"slotid136").alias("slotid136"),
      hashSeq("m137", "string")($"slotid137").alias("slotid137"),
      hashSeq("m138", "string")($"slotid138").alias("slotid138"),
      hashSeq("m139", "string")($"slotid139").alias("slotid139"),
      hashSeq("m140", "string")($"slotid140").alias("slotid140"),
      hashSeq("m141", "string")($"slotid141").alias("slotid141"),
      hashSeq("m142", "string")($"slotid142").alias("slotid142"),
      hashSeq("m143", "string")($"slotid143").alias("slotid143"),
      hashSeq("m144", "string")($"slotid144").alias("slotid144"),
      hashSeq("m145", "string")($"slotid145").alias("slotid145"),
      hashSeq("m146", "string")($"slotid146").alias("slotid146"),
      hashSeq("m147", "string")($"slotid147").alias("slotid147"),
      hashSeq("m148", "string")($"slotid148").alias("slotid148"),
      hashSeq("m149", "string")($"slotid149").alias("slotid149"),
      hashSeq("m150", "string")($"slotid150").alias("slotid150"),
      hashSeq("m151", "string")($"slotid151").alias("slotid151"),
      hashSeq("m152", "string")($"slotid152").alias("slotid152"),
      hashSeq("m153", "string")($"slotid153").alias("slotid153"),
      hashSeq("m154", "string")($"slotid154").alias("slotid154"),
      hashSeq("m155", "string")($"slotid155").alias("slotid155"),
      hashSeq("m156", "string")($"slotid156").alias("slotid156"),
      hashSeq("m157", "string")($"slotid157").alias("slotid157"),
      hashSeq("m158", "string")($"slotid158").alias("slotid158"),
      hashSeq("m159", "string")($"slotid159").alias("slotid159"),
      hashSeq("m160", "string")($"slotid160").alias("slotid160"),
      hashSeq("m161", "string")($"slotid161").alias("slotid161"),
      hashSeq("m162", "string")($"slotid162").alias("slotid162"),
      hashSeq("m163", "string")($"slotid163").alias("slotid163"),
      hashSeq("m164", "string")($"slotid164").alias("slotid164"),
      hashSeq("m165", "string")($"slotid165").alias("slotid165"),
      hashSeq("m166", "string")($"slotid166").alias("slotid166"),
      hashSeq("m167", "string")($"slotid167").alias("slotid167"),
      hashSeq("m168", "string")($"slotid168").alias("slotid168"),
      hashSeq("m169", "string")($"slotid169").alias("slotid169"),
      hashSeq("m170", "string")($"slotid170").alias("slotid170"),
      hashSeq("m171", "string")($"slotid171").alias("slotid171"),
      hashSeq("m172", "string")($"slotid172").alias("slotid172"),
      hashSeq("m173", "string")($"slotid173").alias("slotid173"),
      hashSeq("m174", "string")($"slotid174").alias("slotid174"),
      hashSeq("m175", "string")($"slotid175").alias("slotid175"),
      hashSeq("m176", "string")($"slotid176").alias("slotid176"),
      hashSeq("m177", "string")($"slotid177").alias("slotid177"),
      hashSeq("m178", "string")($"slotid178").alias("slotid178"),
      hashSeq("m179", "string")($"slotid179").alias("slotid179"),
      hashSeq("m180", "string")($"slotid180").alias("slotid180"),
      hashSeq("m181", "string")($"slotid181").alias("slotid181"),
      hashSeq("m182", "string")($"slotid182").alias("slotid182"),
      hashSeq("m183", "string")($"slotid183").alias("slotid183"),
      hashSeq("m184", "string")($"slotid184").alias("slotid184"),
      hashSeq("m185", "string")($"slotid185").alias("slotid185"),
      hashSeq("m186", "string")($"slotid186").alias("slotid186"),
      hashSeq("m187", "string")($"slotid187").alias("slotid187"),
      hashSeq("m188", "string")($"slotid188").alias("slotid188"),
      hashSeq("m189", "string")($"slotid189").alias("slotid189"),
      hashSeq("m190", "string")($"slotid190").alias("slotid190"),
      hashSeq("m191", "string")($"slotid191").alias("slotid191"),
      hashSeq("m192", "string")($"slotid192").alias("slotid192"),
      hashSeq("m193", "string")($"slotid193").alias("slotid193"),
      hashSeq("m194", "string")($"slotid194").alias("slotid194"),
      hashSeq("m195", "string")($"slotid195").alias("slotid195"),
      hashSeq("m196", "string")($"slotid196").alias("slotid196"),
      hashSeq("m197", "string")($"slotid197").alias("slotid197"),
      hashSeq("m198", "string")($"slotid198").alias("slotid198"),
      hashSeq("m199", "string")($"slotid199").alias("slotid199"),
      hashSeq("m200", "string")($"slotid200").alias("slotid200"),
      hashSeq("m201", "string")($"slotid201").alias("slotid201"),
      hashSeq("m202", "string")($"slotid202").alias("slotid202"),
      hashSeq("m203", "string")($"slotid203").alias("slotid203"),
      hashSeq("m204", "string")($"slotid204").alias("slotid204"),
      hashSeq("m205", "string")($"slotid205").alias("slotid205"),
      hashSeq("m206", "string")($"slotid206").alias("slotid206"),
      hashSeq("m207", "string")($"slotid207").alias("slotid207"),
      hashSeq("m208", "string")($"slotid208").alias("slotid208"),
      hashSeq("m209", "string")($"slotid209").alias("slotid209"),
      hashSeq("m210", "string")($"slotid210").alias("slotid210"),
      hashSeq("m211", "string")($"slotid211").alias("slotid211"),
      hashSeq("m212", "string")($"slotid212").alias("slotid212"),
      hashSeq("m213", "string")($"slotid213").alias("slotid213"),
      hashSeq("m214", "string")($"slotid214").alias("slotid214"),
      hashSeq("m215", "string")($"slotid215").alias("slotid215"),
      hashSeq("m216", "string")($"slotid216").alias("slotid216"),
      hashSeq("m217", "string")($"slotid217").alias("slotid217"),
      hashSeq("m218", "string")($"slotid218").alias("slotid218"),
      hashSeq("m219", "string")($"slotid219").alias("slotid219"),
      hashSeq("m220", "string")($"slotid220").alias("slotid220"),
      hashSeq("m221", "string")($"slotid221").alias("slotid221"),
      hashSeq("m222", "string")($"slotid222").alias("slotid222"),
      hashSeq("m223", "string")($"slotid223").alias("slotid223"),
      hashSeq("m224", "string")($"slotid224").alias("slotid224"),
      hashSeq("m225", "string")($"slotid225").alias("slotid225"),
      hashSeq("m226", "string")($"slotid226").alias("slotid226")
    )).alias("sparse")).select($"uid",
      $"label",
      $"sparse".getField("_1").alias("idx0"),
      $"sparse".getField("_2").alias("idx1"),
      $"sparse".getField("_3").alias("idx2"),
      $"sparse".getField("_4").alias("id_arr")
    ).rdd.zipWithUniqueId().map { x =>
        (x._2, x._1.getAs[String]("uid"), x._1.getAs[Seq[Int]]("label"),
          x._1.getAs[Seq[Int]]("idx0"), x._1.getAs[Seq[Int]]("idx1"),
          x._1.getAs[Seq[Int]]("idx2"), x._1.getAs[Seq[Long]]("id_arr")
          )
      }.toDF("sample_idx", "uid", "label", "idx0", "idx1", "idx2", "id_arr")
    sample.repartition(150).write.mode("overwrite").format("tfrecords").option("recordType", "Example").save(s"hdfs://emr-cluster2/user/cpc/sample/recall/dnn_recall_rec_feature/$curday/$hour")
    val writer = new PrintWriter(new File("count"))
    writer.write(spark.sql(
      s"""
         |select uid from dl_cpc.recall_rec_feature where day='$curday' and hour='$hour'
       """.stripMargin).count().toString)
    writer.close()
    s"hadoop fs -put -f count hdfs://emr-cluster2/user/cpc/sample/recall/dnn_recall_rec_feature/$curday/$hour/count" !

  }
  case class featuresResult(var uid: String="",
                             var did: String="",
                             var isclick: Int=0,
                             var slotid1: Seq[String]=null,
                             var slotid2: Seq[String]=null,
                             var slotid3: Seq[String]=null,
                             var slotid4: Seq[String]=null,
                             var slotid5: Seq[String]=null,
                             var slotid6: Seq[String]=null,
                             var slotid7: Seq[String]=null,
                             var slotid8: Seq[String]=null,
                             var slotid9: Seq[String]=null,
                             var slotid10: Seq[String]=null,
                             var slotid11: Seq[String]=null,
                             var slotid12: Seq[String]=null,
                             var slotid13: Seq[String]=null,
                             var slotid14: Seq[String]=null,
                             var slotid15: Seq[String]=null,
                             var slotid16: Seq[String]=null,
                             var slotid17: Seq[String]=null,
                             var slotid18: Seq[String]=null,
                             var slotid19: Seq[String]=null,
                             var slotid20: Seq[String]=null,
                             var slotid21: Seq[String]=null,
                             var slotid22: Seq[String]=null,
                             var slotid23: Seq[String]=null,
                             var slotid24: Seq[String]=null,
                             var slotid25: Seq[String]=null,
                             var slotid26: Seq[String]=null,
                             var slotid27: Seq[String]=null,
                             var slotid28: Seq[String]=null,
                             var slotid29: Seq[String]=null,
                             var slotid30: Seq[String]=null,
                             var slotid31: Seq[String]=null,
                             var slotid32: Seq[String]=null,
                             var slotid33: Seq[String]=null,
                             var slotid34: Seq[String]=null,
                             var slotid35: Seq[String]=null,
                             var slotid36: Seq[String]=null,
                             var slotid37: Seq[String]=null,
                             var slotid38: Seq[String]=null,
                             var slotid39: Seq[String]=null,
                             var slotid40: Seq[String]=null,
                             var slotid41: Seq[String]=null,
                             var slotid42: Seq[String]=null,
                             var slotid43: Seq[String]=null,
                             var slotid44: Seq[String]=null,
                             var slotid45: Seq[String]=null,
                             var slotid46: Seq[String]=null,
                             var slotid47: Seq[String]=null,
                             var slotid48: Seq[String]=null,
                             var slotid49: Seq[String]=null,
                             var slotid50: Seq[String]=null,
                             var slotid51: Seq[String]=null,
                             var slotid52: Seq[String]=null,
                             var slotid53: Seq[String]=null,
                             var slotid54: Seq[String]=null,
                             var slotid55: Seq[String]=null,
                             var slotid56: Seq[String]=null,
                             var slotid57: Seq[String]=null,
                             var slotid58: Seq[String]=null,
                             var slotid59: Seq[String]=null,
                             var slotid60: Seq[String]=null,
                             var slotid61: Seq[String]=null,
                             var slotid62: Seq[String]=null,
                             var slotid63: Seq[String]=null,
                             var slotid64: Seq[String]=null,
                             var slotid65: Seq[String]=null,
                             var slotid66: Seq[String]=null,
                             var slotid67: Seq[String]=null,
                             var slotid68: Seq[String]=null,
                             var slotid69: Seq[String]=null,
                             var slotid70: Seq[String]=null,
                             var slotid71: Seq[String]=null,
                             var slotid72: Seq[String]=null,
                             var slotid73: Seq[String]=null,
                             var slotid74: Seq[String]=null,
                             var slotid75: Seq[String]=null,
                             var slotid76: Seq[String]=null,
                             var slotid77: Seq[String]=null,
                             var slotid78: Seq[String]=null,
                             var slotid79: Seq[String]=null,
                             var slotid80: Seq[String]=null,
                             var slotid81: Seq[String]=null,
                             var slotid82: Seq[String]=null,
                             var slotid83: Seq[String]=null,
                             var slotid84: Seq[String]=null,
                             var slotid85: Seq[String]=null,
                             var slotid86: Seq[String]=null,
                             var slotid87: Seq[String]=null,
                             var slotid88: Seq[String]=null,
                             var slotid89: Seq[String]=null,
                             var slotid90: Seq[String]=null,
                             var slotid91: Seq[String]=null,
                             var slotid92: Seq[String]=null,
                             var slotid93: Seq[String]=null,
                             var slotid94: Seq[String]=null,
                             var slotid95: Seq[String]=null,
                             var slotid96: Seq[String]=null,
                             var slotid97: Seq[String]=null,
                             var slotid98: Seq[String]=null,
                             var slotid99: Seq[String]=null,
                             var slotid100: Seq[String]=null,
                             var slotid101: Seq[String]=null,
                             var slotid102: Seq[String]=null,
                             var slotid103: Seq[String]=null,
                             var slotid104: Seq[String]=null,
                             var slotid105: Seq[String]=null,
                             var slotid106: Seq[String]=null,
                             var slotid107: Seq[String]=null,
                             var slotid108: Seq[String]=null,
                             var slotid109: Seq[String]=null,
                             var slotid110: Seq[String]=null,
                             var slotid111: Seq[String]=null,
                             var slotid112: Seq[String]=null,
                             var slotid113: Seq[String]=null,
                             var slotid114: Seq[String]=null,
                             var slotid115: Seq[String]=null,
                             var slotid116: Seq[String]=null,
                             var slotid117: Seq[String]=null,
                             var slotid118: Seq[String]=null,
                             var slotid119: Seq[String]=null,
                             var slotid120: Seq[String]=null,
                             var slotid121: Seq[String]=null,
                             var slotid122: Seq[String]=null,
                             var slotid123: Seq[String]=null,
                             var slotid124: Seq[String]=null,
                             var slotid125: Seq[String]=null,
                             var slotid126: Seq[String]=null,
                             var slotid127: Seq[String]=null,
                             var slotid128: Seq[String]=null,
                             var slotid129: Seq[String]=null,
                             var slotid130: Seq[String]=null,
                             var slotid131: Seq[String]=null,
                             var slotid132: Seq[String]=null,
                             var slotid133: Seq[String]=null,
                             var slotid134: Seq[String]=null,
                             var slotid135: Seq[String]=null,
                             var slotid136: Seq[String]=null,
                             var slotid137: Seq[String]=null,
                             var slotid138: Seq[String]=null,
                             var slotid139: Seq[String]=null,
                             var slotid140: Seq[String]=null,
                             var slotid141: Seq[String]=null,
                             var slotid142: Seq[String]=null,
                             var slotid143: Seq[String]=null,
                             var slotid144: Seq[String]=null,
                             var slotid145: Seq[String]=null,
                             var slotid146: Seq[String]=null,
                             var slotid147: Seq[String]=null,
                             var slotid148: Seq[String]=null,
                             var slotid149: Seq[String]=null,
                             var slotid150: Seq[String]=null,
                             var slotid151: Seq[String]=null,
                             var slotid152: Seq[String]=null,
                             var slotid153: Seq[String]=null,
                             var slotid154: Seq[String]=null,
                             var slotid155: Seq[String]=null,
                             var slotid156: Seq[String]=null,
                             var slotid157: Seq[String]=null,
                             var slotid158: Seq[String]=null,
                             var slotid159: Seq[String]=null,
                             var slotid160: Seq[String]=null,
                             var slotid161: Seq[String]=null,
                             var slotid162: Seq[String]=null,
                             var slotid163: Seq[String]=null,
                             var slotid164: Seq[String]=null,
                             var slotid165: Seq[String]=null,
                             var slotid166: Seq[String]=null,
                             var slotid167: Seq[String]=null,
                             var slotid168: Seq[String]=null,
                             var slotid169: Seq[String]=null,
                             var slotid170: Seq[String]=null,
                             var slotid171: Seq[String]=null,
                             var slotid172: Seq[String]=null,
                             var slotid173: Seq[String]=null,
                             var slotid174: Seq[String]=null,
                             var slotid175: Seq[String]=null,
                             var slotid176: Seq[String]=null,
                             var slotid177: Seq[String]=null,
                             var slotid178: Seq[String]=null,
                             var slotid179: Seq[String]=null,
                             var slotid180: Seq[String]=null,
                             var slotid181: Seq[String]=null,
                             var slotid182: Seq[String]=null,
                             var slotid183: Seq[String]=null,
                             var slotid184: Seq[String]=null,
                             var slotid185: Seq[String]=null,
                             var slotid186: Seq[String]=null,
                             var slotid187: Seq[String]=null,
                             var slotid188: Seq[String]=null,
                             var slotid189: Seq[String]=null,
                             var slotid190: Seq[String]=null,
                             var slotid191: Seq[String]=null,
                             var slotid192: Seq[String]=null,
                             var slotid193: Seq[String]=null,
                             var slotid194: Seq[String]=null,
                             var slotid195: Seq[String]=null,
                             var slotid196: Seq[String]=null,
                             var slotid197: Seq[String]=null,
                             var slotid198: Seq[String]=null,
                             var slotid199: Seq[String]=null,
                             var slotid200: Seq[String]=null,
                             var slotid201: Seq[String]=null,
                             var slotid202: Seq[String]=null,
                             var slotid203: Seq[String]=null,
                             var slotid204: Seq[String]=null,
                             var slotid205: Seq[String]=null,
                             var slotid206: Seq[String]=null,
                             var slotid207: Seq[String]=null,
                             var slotid208: Seq[String]=null,
                             var slotid209: Seq[String]=null,
                             var slotid210: Seq[String]=null,
                             var slotid211: Seq[String]=null,
                             var slotid212: Seq[String]=null,
                             var slotid213: Seq[String]=null,
                             var slotid214: Seq[String]=null,
                             var slotid215: Seq[String]=null,
                             var slotid216: Seq[String]=null,
                             var slotid217: Seq[String]=null,
                             var slotid218: Seq[String]=null,
                             var slotid219: Seq[String]=null,
                             var slotid220: Seq[String]=null,
                             var slotid221: Seq[String]=null,
                             var slotid222: Seq[String]=null,
                             var slotid223: Seq[String]=null,
                             var slotid224: Seq[String]=null,
                             var slotid225: Seq[String]=null,
                             var slotid226: Seq[String]=null
                           )

  private def mkSparseFeature_m = udf {
    features: Seq[Seq[Long]] =>
      var i = 0
      var re = Seq[(Int, Int, Long)]()
      for (feature <- features) {
        re = re ++
          (if (feature != null) feature.zipWithIndex.map(x => (i, x._2, x._1)) else default_hash(i))
        i = i + 1
      }
      val c = re.map(x => (0, x._1, x._2, x._3))
      (c.map(_._1), c.map(_._2), c.map(_._3), c.map(_._4))
  }

  private def hashSeq(prefix: String, t: String) = {
    t match {
      case "int" => udf {
        seq: Seq[Int] =>
          val re = if (seq != null && seq.nonEmpty) for (i <- seq) yield Murmur3Hash.stringHash64(prefix + i, 0)
          else Seq(Murmur3Hash.stringHash64(prefix, 0))
          re.slice(0, 1000)
      }
      case "string" => udf {
        seq: Seq[String] =>
          val re = if (seq != null && seq.nonEmpty) for (i <- seq) yield Murmur3Hash.stringHash64(prefix + i, 0)
          else Seq(Murmur3Hash.stringHash64(prefix, 0))
          re.slice(0, 1000)
      }
    }
  }
}
