create table test.ocpc_report_data_hourly (
    ideaid                  int,
    unitid                  int,
    userid                  int,
    prod_name               string,
    adclass                 int,
    adslot_type             int,
    adslotid                string,
    conversion_goal         int,
    deep_conversion_goal    int,
    cpa_check_priority      int,
    media_appsid            string,
    ocpc_expand             int,
    show                    bigint,
    click                   bigint,
    cv1                     bigint,
    cv2                     bigint,
    total_price             bigint,
    total_bid               bigint,
    total_precvr            double,
    total_rawcvr            double,
    total_prectr            double,
    total_exp_cpm           double,
    total_cpagiven          double,
    total_jfbfactor         double,
    total_cvrfactor         double,
    total_calipcvr          double,
    total_discrete_factor   double,
    total_shallow_bid       double,
    bl_hidden_tax           bigint,
    bk_hidden_tax           bigint,
    total_deep_cpagiven     double,
    total_deep_jfbfactor    double,
    total_deep_cvrfactor    double,
    total_deep_calipcvr     double,
    total_deep_bid          double,
    total_deepcvr           double,
    ocpc_stage              int
)
partitioned by (`date` string, `hour` string)
stored as parquet;